### ISSUE TITLE
release versions

### ISSUE THREAD

**Issue by meisam-wiki** [Kizoky/Mr_SmileyII#6]
Please rename this release and fix its version:
https://github.com/Kizoky/Mr_SmileyII/releases/tag/SEP_02_2017

**Comment by Kizoky** [comment]
What's wrong with it?

Updated the title of the release: https://github.com/Kizoky/Mr_SmileyII/releases/tag/Zandro_2.1.2
The reason why Zandronum's version number is shown instead of the mod's version number, is because after v0.50 the mod will refuse to work with Zandronum, and other source ports that don't have ZScript.

**Comment by meisam-wiki** [comment]
You can see the effects of your versioning style here: https://www.wikidata.org/w/index.php?title=Q67471766&oldid=1013081866#Q67471766$4d2a0dd2-ecd3-4f9c-9ce3-bbb510a5171e

**Comment by Kizoky** [comment]
Updated: https://github.com/Kizoky/Mr_SmileyII/releases/tag/v0.49
Old tags removed

**Comment by meisam-wiki** [comment]
Thanks! I will wait for the Github-wiki-bot to update the releases and check the results.
